server:
    port: 8088
spring:
    devtools:
        restart:
            # 热部署生效
            enabled: false
            # 设置重启目录
            additional-paths: src/main/java
            # 设置排除目录
            exclude: src/main/resources/static
    jmx:
        enabled: false
    mvc:
        # 静态资源访问路径
        static-path-pattern: static/**
    web:
        resources:
            # 静态资源存储路径
            static-locations: /upload/
    servlet:
        multipart:
            # 最大上传单文件大小
            max-file-size: 10MB
            # 最大上传总大小
            max-request-size: 10MB