server:
    port: 8088
spring:
    devtools:
        restart:
            # 热部署生效
            enabled: false
            # 设置重启目录
            additional-paths: src/main/java
            # 设置排除目录
            exclude: src/main/resources/static
    jmx:
        enabled: false
    mvc:
        # 静态资源访问路径
#        static-path-pattern: static/**
        pathmatch:
            matching-strategy: ant_path_matcher
    web:
        resources:
            # 静态资源存储路径
#            static-locations: /upload/
    servlet:
        multipart:
            # 最大上传单文件大小
            max-file-size: 10MB
            # 最大上传总大小
            max-request-size: 10MB
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://58.87.103.30:3306/liulaoshi?serverTimezone=GMT%2B8
        username: tiankai
        password: Qq133242
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl